FROM alpine:3.7

MAINTAINER ingildsens (https://github.com/ingildsens)


RUN \

# New user creation
#addgroup -S app &&\
#adduser -D -G app maintainer &&\
#passwd maintainer -d test1234



addgroup -S app &&\
adduser maintainer -D &&\
passwd maintainer -d test1234 &&\
sed -i 's/app:x:101:/app:x:101:maintainer/g' /etc/group


ENTRYPOINT ["/bin/sh"]
