FROM alpine:3.7

MAINTAINER ingildsens (https://github.com/ingildsens)


RUN \

# New user creation
adduser ladmin -D \
passwd ladmin -d test1234 \
sed -i 's/ladmin:x:1000:/ladmin:x:1000:root/g' /etc/group


ENTRYPOINT ["/bin/sh"]
